version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
      - CACHE_DRIVER=redis
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel_db
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: laravel_redis
    ports:
      - "6380:6379"
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
    driver: bridge
